/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vamartid.test1._email;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.awt.event.*;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static vamartid.test1._email.MY_socket_CLIENT.PORT;

/**
 *
 * @author basilism
 */
public class Z_Email extends javax.swing.JFrame {

    int xmouse;
    int ymouse;
    int bsOFF = 0;
    Socket SOCK=null;
    /**
     * 
     * @param a ___
     * @param z ___
     */
    public Z_Email(String a,Socket z) {
        SOCK=z;
        initComponents();
        Dimension screenSize = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setPreferredSize(new Dimension(490, 540));
        Dimension windowSize = new Dimension(getPreferredSize());
        int wdwLeft = 230 + screenSize.width / 2 - windowSize.width / 2;
        int wdwTop = 40 + screenSize.height / 2 - windowSize.height / 2;
        pack();
        setLocation(wdwLeft, wdwTop);
        this.from.setText(a);
//////        if(){
//////            System.exit(0);
//////        }

    }

    //diavase to mail
    /**
     * 
     * @param a ___
     * @param b ___
     * @param c ___
     * @param d ___
     * @param z ___
     */
    public Z_Email(String a, String b, String c, String d,Socket z) {
        SOCK=z;
        initComponents();
        Dimension screenSize = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setPreferredSize(new Dimension(490, 540));
        Dimension windowSize = new Dimension(getPreferredSize());
        int wdwLeft = 230 + screenSize.width / 2 - windowSize.width / 2;
        int wdwTop = 40 + screenSize.height / 2 - windowSize.height / 2;
        pack();
        setLocation(wdwLeft, wdwTop);
        this.from.setText(a);
        this.to.setText(b);
        this.subject.setText(c);
        this.jTextArea1.setText(d);
    }
    /**
     * 
     * @param a ___
     * @param b ___
     * @param c ___
     * @param d ___
     * @param setfalse ___
     * @param z  ___
     */
    public Z_Email(String a, String b, String c, String d, boolean setfalse,Socket z) {
        SOCK=z;

        initComponents();
        Dimension screenSize = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setPreferredSize(new Dimension(490, 540));
        Dimension windowSize = new Dimension(getPreferredSize());
        int wdwLeft = 230 + screenSize.width / 2 - windowSize.width / 2;
        int wdwTop = 40 + screenSize.height / 2 - windowSize.height / 2;
        pack();
        setLocation(wdwLeft, wdwTop);
        this.from.setText(a);
        this.from.setEditable(setfalse);
        this.to.setText(b);
        this.to.setEditable(setfalse);
        this.subject.setText(c);
        this.subject.setEditable(setfalse);
        
//        String D[]=d.split("::::");
//        for(int i=0;i<D.length;i++){
//            
//            this.jTextArea1.append(jTextArea1.getText()+"\n"+D[i]);
//        }
                    this.jTextArea1.append(d);

        this.jTextArea1.setEditable(setfalse);
         this.remove(send);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        from = new javax.swing.JTextField();
        subject = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        min1 = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        dragable = new javax.swing.JLabel();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(490, 540));
        setMinimumSize(new java.awt.Dimension(490, 540));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        from.setEditable(false);
        from.setColumns(1);
        from.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        from.setForeground(new java.awt.Color(211, 84, 0));
        from.setText("currentuser");
        from.setToolTipText("Αποστολέας");
        from.setBorder(null);
        from.setName(""); // NOI18N
        from.setOpaque(false);
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        getContentPane().add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 36, 370, 30));

        subject.setColumns(1);
        subject.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        subject.setForeground(new java.awt.Color(211, 84, 0));
        subject.setToolTipText("Θέμα μηνύματος");
        subject.setBorder(null);
        subject.setName(""); // NOI18N
        subject.setOpaque(false);
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        subject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                subjectKeyTyped(evt);
            }
        });
        getContentPane().add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 99, 370, 32));

        to.setColumns(1);
        to.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        to.setForeground(new java.awt.Color(211, 84, 0));
        to.setToolTipText("Παραλήπτης");
        to.setBorder(null);
        to.setName(""); // NOI18N
        to.setOpaque(false);
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        to.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                toKeyTyped(evt);
            }
        });
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 67, 370, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(211, 84, 0));
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Περιεχόμενο μηνύματος");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 490, 350));

        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vamartid/test1/buttons/saA.png"))); // NOI18N
        send.setToolTipText("Αποστολή");
        send.setBorder(null);
        send.setBorderPainted(false);
        send.setContentAreaFilled(false);
        send.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send.setFocusPainted(false);
        send.setPreferredSize(new java.awt.Dimension(32, 9));
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sendMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sendMouseReleased(evt);
            }
        });
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 495, 100, 36));

        min1.setToolTipText("Σμίκρυνση παραθύρου");
        min1.setBorder(null);
        min1.setBorderPainted(false);
        min1.setContentAreaFilled(false);
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.setFocusPainted(false);
        min1.setPreferredSize(new java.awt.Dimension(32, 9));
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                min1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                min1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                min1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                min1MouseReleased(evt);
            }
        });
        min1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min1ActionPerformed(evt);
            }
        });
        getContentPane().add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 0, 47, 32));

        close.setToolTipText("Κλείσιμο παραθύρου");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 0, 47, 32));

        dragable.setToolTipText("");
        dragable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragableMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dragableMouseMoved(evt);
            }
        });
        dragable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragableMousePressed(evt);
            }
        });
        getContentPane().add(dragable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 32));

        backround.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vamartid/test1/images/Untitled-2.png"))); // NOI18N
        getContentPane().add(backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        //create the mail
        if (!(this.bsOFF == 50)) {

            Email a = new Email(this.from.getText(), this.to.getText(), this.subject.getText(), this.jTextArea1.getText());
            MY_socket_CLIENT CLIENT = new MY_socket_CLIENT();
            try {
                //Socket SOCK = new Socket("localhost", PORT);
                CLIENT.send_orders("new",SOCK);
                CLIENT.send_mail(a,SOCK) ;
            } catch (IOException ex) {
                Logger.getLogger(Z_Email.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Z_Email.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_sendActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void min1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min1ActionPerformed
        // TODO add your handling code here:
//        min1.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent ae) {
//                setState(ICONIFIED);
//            }
//        });
        this.setState(ICONIFIED);
        //  this.setVisible(false);
    }//GEN-LAST:event_min1ActionPerformed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        // TODO add your handling code here:
        close.setIcon(null);
        //an boresw na  kanw refresh ta mails logo tou oti me to pou klisei ena tetoio
        //jframe yparxrei 50% pithanotita o xristis na exei diavasei ena kainourio
        //refresh();
        this.dispose();
    }//GEN-LAST:event_closeMouseReleased

    private void min1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/B.png"));
        min1.setIcon(II);
    }//GEN-LAST:event_min1MouseEntered

    private void min1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseExited
        // TODO add your handling code here:
        min1.setIcon(null);

    }//GEN-LAST:event_min1MouseExited

    private void min1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/C.png"));
        min1.setIcon(II);
    }//GEN-LAST:event_min1MousePressed

    private void min1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseReleased
        // TODO add your handling code here:
        min1.setIcon(null);

    }//GEN-LAST:event_min1MouseReleased

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/xA.png"));
        close.setIcon(II);
    }//GEN-LAST:event_closeMousePressed

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setIcon(null);

    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/xB.png"));
        close.setIcon(II);
    }//GEN-LAST:event_closeMouseEntered

    private void sendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseEntered
        // TODO add your handling code here:
        if (!(this.bsOFF == 50)) {

            ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/saB.png"));
            send.setIcon(II);
        }
    }//GEN-LAST:event_sendMouseEntered

    private void sendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseExited
        // TODO add your handling code here:
        if (!(this.bsOFF == 50)) {

            ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/saA.png"));
            send.setIcon(II);
        }
    }//GEN-LAST:event_sendMouseExited

    private void sendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMousePressed
        if (!(this.bsOFF == 50)) {

            // TODO add your handling code here:
            ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/saC.png"));
            send.setIcon(II);
        }
    }//GEN-LAST:event_sendMousePressed

    private void sendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseReleased
        if (!(this.bsOFF == 50)) {

            // TODO add your handling code here:
            ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/saA.png"));
            send.setIcon(II);
            this.setVisible(false);
            if (true) {
                this.dispose();
            };
        }

    }//GEN-LAST:event_sendMouseReleased

    private void dragableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragableMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();

        int y = evt.getYOnScreen();

//System.out.println(x+" "+y);
        this.setLocation(x - xmouse, y - ymouse);

    }//GEN-LAST:event_dragableMouseDragged

    private void dragableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragableMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_dragableMouseMoved

    private void dragableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragableMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();

        ymouse = evt.getY();
    }//GEN-LAST:event_dragableMousePressed

    private void toKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_toKeyTyped

    private void subjectKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c >= 32 && c <= 47) ||(c >= 58 && c <= 64) || (c >= 91 && c <= 96) || (c >= 123 && c <= 126) || c == '?') {
            evt.consume();  // ignore event
        }

        String s = to.getText();
        //System.out.println("klaimera"+s);
        int a = 0;
        if (s.length() == 40) {
            a = 1;
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_subjectKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Z_Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Z_Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Z_Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Z_Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Z_Email().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backround;
    private javax.swing.JLabel close;
    private javax.swing.JLabel dragable;
    private javax.swing.JTextField from;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton min1;
    private javax.swing.JButton send;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
