/*
 * License Copyright © 2000 Vasileios Martidis vamartid@yandex.com 
 * This work is free. You can redistribute it and/or modify it under
 *  the terms of the Do What The Fuck You Want To Public License,
 *  Version 2, as published by Sam Hocevar.
 *  See http://www.wtfpl.net/ for more details.
 */
package vamartid.test1._email;

import vamartid.test1.validate.ValidatorDate;
import vamartid.test1.validate.ValidatorMail;
import java.awt.Frame;
import javax.swing.JFrame;
import java.awt.event.*;
import static java.awt.event.KeyEvent.VK_BACK_SPACE;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static vamartid.test1._email.MY_socket_CLIENT.PORT;

/**
 *
 * @author basilism
 */
public class Z_singup extends javax.swing.JFrame {

    int xmouse;
    int ymouse;
    String passsss = "";
    String confirm = "";
    Socket SOCK =null;
    /**
     * 
     * @param a  ___
     */
    public Z_singup(Socket a) {
        SOCK=a;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create = new javax.swing.JButton();
        new_last = new javax.swing.JTextField();
        new_first = new javax.swing.JTextField();
        new_username = new javax.swing.JTextField();
        new_pass = new javax.swing.JTextField();
        new_pass_confirm = new javax.swing.JTextField();
        new_birthday = new javax.swing.JTextField();
        new_currentmail = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        min1 = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        kapa = new javax.swing.JLabel();
        kapa2 = new javax.swing.JLabel();
        kapa3 = new javax.swing.JLabel();
        kapa4 = new javax.swing.JLabel();
        dragable = new javax.swing.JLabel();
        kapa5 = new javax.swing.JLabel();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(330, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create.setToolTipText("Εγγραφή");
        create.setBorder(null);
        create.setBorderPainted(false);
        create.setContentAreaFilled(false);
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.setFocusPainted(false);
        create.setPreferredSize(new java.awt.Dimension(32, 9));
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                createMouseReleased(evt);
            }
        });
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 552, 112, 36));

        new_last.setColumns(1);
        new_last.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        new_last.setForeground(new java.awt.Color(255, 255, 255));
        new_last.setText(" Enter your LastName");
        new_last.setToolTipText("Επώνυμο");
        new_last.setBorder(null);
        new_last.setName(""); // NOI18N
        new_last.setOpaque(false);
        new_last.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_lastFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_lastFocusLost(evt);
            }
        });
        new_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_lastActionPerformed(evt);
            }
        });
        new_last.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                new_lastKeyTyped(evt);
            }
        });
        getContentPane().add(new_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 231, 270, 30));

        new_first.setColumns(1);
        new_first.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        new_first.setForeground(new java.awt.Color(255, 255, 255));
        new_first.setText(" Enter your FirstName");
        new_first.setToolTipText("Όνομα");
        new_first.setBorder(null);
        new_first.setName(""); // NOI18N
        new_first.setOpaque(false);
        new_first.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_firstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_firstFocusLost(evt);
            }
        });
        new_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_firstActionPerformed(evt);
            }
        });
        new_first.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                new_firstKeyTyped(evt);
            }
        });
        getContentPane().add(new_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 183, 270, 30));

        new_username.setColumns(1);
        new_username.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        new_username.setForeground(new java.awt.Color(255, 255, 255));
        new_username.setText(" Enter a username");
        new_username.setToolTipText("Το ονομα με το οποιο θα κανετε σύνδση");
        new_username.setBorder(null);
        new_username.setName(""); // NOI18N
        new_username.setOpaque(false);
        new_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_usernameFocusLost(evt);
            }
        });
        new_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_usernameActionPerformed(evt);
            }
        });
        new_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                new_usernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                new_usernameKeyTyped(evt);
            }
        });
        getContentPane().add(new_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 286, 270, 30));

        new_pass.setColumns(1);
        new_pass.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        new_pass.setForeground(new java.awt.Color(255, 255, 255));
        new_pass.setText(" Enter a password");
        new_pass.setToolTipText("Ο κώδικος που θα απαιτήται για την σύνδεση");
        new_pass.setBorder(null);
        new_pass.setName(""); // NOI18N
        new_pass.setOpaque(false);
        new_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_passFocusLost(evt);
            }
        });
        new_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_passActionPerformed(evt);
            }
        });
        new_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                new_passKeyTyped(evt);
            }
        });
        getContentPane().add(new_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 342, 270, 30));

        new_pass_confirm.setColumns(1);
        new_pass_confirm.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        new_pass_confirm.setForeground(new java.awt.Color(255, 255, 255));
        new_pass_confirm.setText(" Retype the password");
        new_pass_confirm.setToolTipText("Επιβεβαίωση του κωδίκου πρόσβασης");
        new_pass_confirm.setBorder(null);
        new_pass_confirm.setCaretPosition(17);
        new_pass_confirm.setName(""); // NOI18N
        new_pass_confirm.setOpaque(false);
        new_pass_confirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_pass_confirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_pass_confirmFocusLost(evt);
            }
        });
        new_pass_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_pass_confirmActionPerformed(evt);
            }
        });
        new_pass_confirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                new_pass_confirmKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                new_pass_confirmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                new_pass_confirmKeyTyped(evt);
            }
        });
        getContentPane().add(new_pass_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 398, 270, 30));

        new_birthday.setColumns(1);
        new_birthday.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        new_birthday.setForeground(new java.awt.Color(255, 255, 255));
        new_birthday.setText(" Your birthday mm/dd/yy");
        new_birthday.setToolTipText("Γενέθλια σε μορφή ημέρες/μηνες/χρόνια");
        new_birthday.setBorder(null);
        new_birthday.setName(""); // NOI18N
        new_birthday.setOpaque(false);
        new_birthday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_birthdayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_birthdayFocusLost(evt);
            }
        });
        new_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_birthdayActionPerformed(evt);
            }
        });
        new_birthday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                new_birthdayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                new_birthdayKeyTyped(evt);
            }
        });
        getContentPane().add(new_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 457, 270, 30));

        new_currentmail.setColumns(1);
        new_currentmail.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        new_currentmail.setForeground(new java.awt.Color(255, 255, 255));
        new_currentmail.setText(" Enter your address");
        new_currentmail.setToolTipText("Τωρινή διεύθινση email");
        new_currentmail.setBorder(null);
        new_currentmail.setName(""); // NOI18N
        new_currentmail.setOpaque(false);
        new_currentmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                new_currentmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                new_currentmailFocusLost(evt);
            }
        });
        new_currentmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_currentmailActionPerformed(evt);
            }
        });
        new_currentmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                new_currentmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                new_currentmailKeyTyped(evt);
            }
        });
        getContentPane().add(new_currentmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 513, 270, 30));

        back.setToolTipText("Μετάβαση στο αρχικό μενού");
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setFocusPainted(false);
        back.setPreferredSize(new java.awt.Dimension(32, 9));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backMouseReleased(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 47, 32));

        min1.setToolTipText("Σμίκρυνση παραθύρου");
        min1.setBorder(null);
        min1.setBorderPainted(false);
        min1.setContentAreaFilled(false);
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.setFocusPainted(false);
        min1.setPreferredSize(new java.awt.Dimension(32, 9));
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                min1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                min1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                min1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                min1MouseReleased(evt);
            }
        });
        min1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min1ActionPerformed(evt);
            }
        });
        getContentPane().add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 0, 47, 32));

        close.setToolTipText("Κλείσιμο παραθύρου");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 0, 47, 32));
        getContentPane().add(kapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 513, 30, 30));
        getContentPane().add(kapa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 456, 30, 30));
        getContentPane().add(kapa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 399, 30, 30));
        getContentPane().add(kapa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 285, 30, 30));

        dragable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragableMouseDragged(evt);
            }
        });
        dragable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragableMousePressed(evt);
            }
        });
        dragable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dragableKeyPressed(evt);
            }
        });
        getContentPane().add(dragable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 32));
        getContentPane().add(kapa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 554, 30, 30));

        backround.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vamartid/test1/images/singup2.png"))); // NOI18N
        backround.setRequestFocusEnabled(false);
        getContentPane().add(backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        if (!(new_username.getText().equals(" Enter a username")
                || (new_pass.getText().equals(" Enter a password"))
                || (new_first.getText().equals(" Enter your FirstName"))
                || (new_last.getText().equals(" Enter your LastName"))
                || (new_birthday.getText().equals(" Your birthday mm/dd/yy"))
                || (new_currentmail.equals(" Enter your address")))) {
            Account theNewOne = new Account(new_username.getText(),
                    new_first.getText(),
                    new_last.getText(),
                    passsss,
                    new_birthday.getText(),
                    new_currentmail.getText());

////        String nf = new_first.getText();
////        String nl = new_last.getText();
////        String nu = new_username.getText();
////        String np = new_pass.getText();
////        String npc = new_pass_confirm.getText();
////        String nb = new_birthday.getText();
////        String nc = new_currentmail.getText();
            int m = 0;
////        String all = new_first.getText() + "::::"
////                + new_last.getText() + "::::"
////                + new_username.getText() + "::::"
////                + new_pass.getText() + "::::"
////                + new_birthday.getText() + "::::" + new_currentmail.getText();

            if (passsss.equals(confirm)) {
                ValidatorMail emailValidator = new ValidatorMail();
                if (!emailValidator.validate(new_currentmail.getText().trim())) {
                    System.out.print("Invalid Email ID");
                    System.out.print("Re-insert Email ID");
                    m = 1;
                }
                ValidatorDate dateValidator = new ValidatorDate();
                if (!dateValidator.validate(new_birthday.getText().trim())) {
                    System.out.print("Invalid Birthday");
                    System.out.print("Re-insert Birthday");
                    m = 1;
                }
                if (m == 0) {
                    boolean done = false;
                    System.out.print(done);
                    MY_socket_CLIENT CLIENT = new MY_socket_CLIENT();
                    try {
                        //Socket SOCK = new Socket("localhost", PORT);
                        CLIENT.send_orders("register", SOCK);
                        done = CLIENT.register(theNewOne, SOCK);
                    } catch (IOException ex) {
                        Logger.getLogger(Z_singup.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception ex) {
                        Logger.getLogger(Z_singup.class.getName()).log(Level.SEVERE, null, ex);
                    }
            //Stelnw stoixeia ston Server kai aytos kanei tin parakaw synartisi
                    //Stelnw to String all
                    //boolean done = false;
                    //dexomai boolean kai typonw analoga

                    ImageIcon b = new ImageIcon();
                    if (done) {
                        System.out.println("Your account has been created!");
                        b = new ImageIcon(getClass().getResource("/vamartid/test1/images/V.png"));
                        kapa5.setIcon(b);
                    } else {
                        System.out.println("Username already exist,try another one.");
                        b = new ImageIcon(getClass().getResource("/vamartid/test1/images/X.png"));
                        kapa4.setIcon(b);
                        kapa5.setIcon(b);

                    }
                }
            } else {
                System.out.println("Please re-insert the password and the password confirmation");
            }
        } else {
            System.out.println("Some data are not declared");
        }
    }//GEN-LAST:event_createActionPerformed

    private void new_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_usernameActionPerformed

    private void new_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_lastActionPerformed

    private void new_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_firstActionPerformed

    private void new_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_passActionPerformed

    private void new_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_birthdayActionPerformed

    private void new_currentmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_currentmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_currentmailActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        try {
            new Z_menu(SOCK).setVisible(true); // Main Form to show after the Login Form..
        } catch (IOException ex) {
            Logger.getLogger(Z_singup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backActionPerformed

    private void min1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min1ActionPerformed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_min1ActionPerformed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        // TODO add your handling code here:
        MY_socket_CLIENT CLIENT = new MY_socket_CLIENT();
                    try {
                        //Socket SOCK = new Socket("localhost", PORT);
                        CLIENT.send_orders("exit",SOCK);
                    } catch (IOException ex) {
                        Logger.getLogger(Z_user.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception ex) {
                        Logger.getLogger(Z_user.class.getName()).log(Level.SEVERE, null, ex);
                    }
        close.setIcon(null);
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/B.png"));
        back.setIcon(II);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setIcon(null);
    }//GEN-LAST:event_backMouseExited

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/C.png"));
        back.setIcon(II);
    }//GEN-LAST:event_backMousePressed

    private void backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseReleased
        // TODO add your handling code here:
        back.setIcon(null);
    }//GEN-LAST:event_backMouseReleased

    private void min1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/B.png"));
        min1.setIcon(II);
    }//GEN-LAST:event_min1MouseEntered

    private void min1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseExited
        // TODO add your handling code here:
        min1.setIcon(null);

    }//GEN-LAST:event_min1MouseExited

    private void min1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/C.png"));
        min1.setIcon(II);
    }//GEN-LAST:event_min1MousePressed

    private void min1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseReleased
        // TODO add your handling code here:
        min1.setIcon(null);

    }//GEN-LAST:event_min1MouseReleased

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/xB.png"));
        close.setIcon(II);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setIcon(null);
    }//GEN-LAST:event_closeMouseExited

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/xA.png"));
        close.setIcon(II);
    }//GEN-LAST:event_closeMousePressed

    private void createMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/crB.png"));
        create.setIcon(II);
    }//GEN-LAST:event_createMouseEntered

    private void createMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseExited
        // TODO add your handling code here:
        create.setIcon(null);
    }//GEN-LAST:event_createMouseExited

    private void createMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/crC.png"));
        create.setIcon(II);
    }//GEN-LAST:event_createMousePressed

    private void createMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseReleased
        // TODO add your handling code here:
        create.setIcon(null);
    }//GEN-LAST:event_createMouseReleased

    private void new_firstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_firstFocusGained
        // TODO add your handling code here:
        kapa5.setIcon(null);
        if (new_first.getText().equals(" Enter your FirstName")) {
            new_first.setText("");
        }
    }//GEN-LAST:event_new_firstFocusGained

    private void new_firstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_firstFocusLost
        // TODO add your handling code here:

        if (new_first.getText().equals("")) {
            new_first.setText(" Enter your FirstName");
        }
    }//GEN-LAST:event_new_firstFocusLost

    private void new_lastFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_lastFocusGained
        // TODO add your handling code here:
        kapa5.setIcon(null);
        
        
        if (new_last.getText().equals(" Enter your LastName")) {
            new_last.setText("");
        }
    }//GEN-LAST:event_new_lastFocusGained

    private void new_lastFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_lastFocusLost
        // TODO add your handling code here:
        if (new_last.getText().equals("")) {
            new_last.setText(" Enter your LastName");
        }
    }//GEN-LAST:event_new_lastFocusLost

    private void new_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_usernameFocusGained
        // TODO add your handling code here:
        kapa4.setIcon(null);
        kapa5.setIcon(null);
        if (new_username.getText().equals(" Enter a username")) {
            new_username.setText("");
        }
    }//GEN-LAST:event_new_usernameFocusGained

    private void new_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_usernameFocusLost
        // TODO add your handling code here:
        if (new_username.getText().equals("")) {
            new_username.setText(" Enter a username");
        }
    }//GEN-LAST:event_new_usernameFocusLost

    private void new_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_passFocusGained
        // TODO add your handling code here:
        kapa5.setIcon(null);
        
        if (new_pass.getText().equals(" Enter a password")) {
            new_pass.setText("");
        }
    }//GEN-LAST:event_new_passFocusGained

    private void new_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_passFocusLost
        // TODO add your handling code here:
        if (new_pass.getText().equals("")) {
            new_pass.setText(" Enter a password");
        }
    }//GEN-LAST:event_new_passFocusLost

    private void new_birthdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_birthdayFocusGained
        // TODO add your handling code here:
        kapa5.setIcon(null);
        if (new_birthday.getText().equals(" Your birthday mm/dd/yy")) {
            new_birthday.setText("");
        }
    }//GEN-LAST:event_new_birthdayFocusGained

    private void new_birthdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_birthdayFocusLost
        // TODO add your handling code here:
        kapa2.setIcon(null);
        if (new_birthday.getText().equals("")) {
            new_birthday.setText(" Your birthday mm/dd/yy");
        }
    }//GEN-LAST:event_new_birthdayFocusLost

    private void new_currentmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_currentmailFocusGained
        // TODO add your handling code here:
        kapa5.setIcon(null);
        if (new_currentmail.getText().equals(" Enter your address")) {
            new_currentmail.setText("");
        }
    }//GEN-LAST:event_new_currentmailFocusGained

    private void new_currentmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_currentmailFocusLost
        kapa.setIcon(null);
        if (new_currentmail.getText().equals("")) {
            new_currentmail.setText(" Enter your address");

        }
    }//GEN-LAST:event_new_currentmailFocusLost

    private void new_firstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_firstKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c >= 32 && c <= 64) || (c >= 91 && c <= 96) || (c >= 123 && c <= 126) || c == '?') {
            evt.consume();  // ignore event
        }

        String s = new_last.getText();
        //System.out.println("klaimera"+s);
        int a = 0;
        if (s.length() == 15) {
            a = 1;
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_new_firstKeyTyped

    private void new_lastKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_lastKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c >= 32 && c <= 64) || (c >= 91 && c <= 96) || (c >= 123 && c <= 126) || c == '?') {
            evt.consume();  // ignore event
        }

        String s = new_last.getText();
        //System.out.println("klaimera"+s);
        int a = 0;
        if (s.length() == 15) {
            a = 1;
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_new_lastKeyTyped

    private void new_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_usernameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == ':') {
            evt.consume();  // ignore event
        }

//        String s = new_username.getText();
        //System.out.println("klaimera"+s);
//        int a = 0;
//        if (s.length() == 15) {
//            a = 1;
//            getToolkit().beep();
//            evt.consume();
//        }
    }//GEN-LAST:event_new_usernameKeyTyped

    private void new_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_passKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == ':') {
            evt.consume();  // ignore event
        } else if (evt.getKeyChar() == VK_BACK_SPACE) {
            String abc = new_pass.getText();
            if (!(abc.length() == 0)) {
                new_pass.setText(abc.substring(0, abc.length() - 1));
                String stringValueOf = String.valueOf(c);
                passsss = passsss + stringValueOf;
                evt.consume();
                new_pass.setText(new_pass.getText() + "*");
                //System.out.println(passsss);
            } else {
                new_pass.setText("");
                passsss = "";
            }
        } else {

            String stringValueOf = String.valueOf(c);
            passsss = passsss + stringValueOf;
            evt.consume();
            new_pass.setText(new_pass.getText() + "*");
            //System.out.println(passsss);
        }
    }//GEN-LAST:event_new_passKeyTyped

    private void new_birthdayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_birthdayKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c >= 32 && c <= 46) || (c >= 58 && c <= 126)) {
            evt.consume();  // ignore event
        }

        String s = new_birthday.getText();
        //System.out.println("klaimera"+s);
        int a = 0;
        if (s.length() == 10) {
            a = 1;
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_new_birthdayKeyTyped

    private void new_currentmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_currentmailKeyTyped

//         TODO add your handling code here:
//        char c = evt.getKeyChar();
//        if (!((c >= 48 && c <= 57) ||
//                (c >= 65 && c <=90)||
//                (c >= 97 && c <=122)||
//                (c >= 35 && c <=39)||
//                (c >= 42 && c <=45)||
//                (c >= 94 && c <=96)||
//                (c >= 123 && c <=126)||(c==33)||(c==47)||(c==61)||(c==63))){
//        evt.consume();  // ignore event
//        }
//                                    String s = new_currentmail.getText();
////                                    Boolean bool;
////                                    //System.out.println("klaimera"+s);
////                                    EmailFormatValidatorTest emailFormatValidator=new EmailFormatValidatorTest(s, false);
////                                    emailFormatValidator.test();
////                                    System.out.println();
//        int a = 0;
//        if (s.length() == 8) {
//            a = 1;
//            getToolkit().beep();
//            evt.consume();
//        }
//        
    }//GEN-LAST:event_new_currentmailKeyTyped

    private void dragableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dragableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dragableKeyPressed

    private void dragableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragableMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();

        ymouse = evt.getY();
    }//GEN-LAST:event_dragableMousePressed

    private void dragableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragableMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();

        int y = evt.getYOnScreen();

//System.out.println(x+" "+y);
        this.setLocation(x - xmouse, y - ymouse);

    }//GEN-LAST:event_dragableMouseDragged

    private void new_birthdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_birthdayKeyReleased
        // TODO add your handling code here:
        ValidatorDate dateValidator = new ValidatorDate();
        ImageIcon b = new ImageIcon();
        if (!dateValidator.validate(new_birthday.getText().trim())) {
            b = new ImageIcon(getClass().getResource("/vamartid/test1/images/X.png"));
            kapa2.setIcon(b);
        } else {
            b = new ImageIcon(getClass().getResource("/vamartid/test1/images/V.png"));
            kapa2.setIcon(b);
        }
    }//GEN-LAST:event_new_birthdayKeyReleased

    private void new_currentmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_currentmailKeyReleased
        // TODO add your handling code here:
        ValidatorMail emailValidator = new ValidatorMail();
        ImageIcon a = new ImageIcon();
        if (!emailValidator.validate(new_currentmail.getText().trim())) {
            a = new ImageIcon(getClass().getResource("/vamartid/test1/images/X.png"));
            kapa.setIcon(a);
        } else {
            a = new ImageIcon(getClass().getResource("/vamartid/test1/images/V.png"));
            kapa.setIcon(a);
        }
    }//GEN-LAST:event_new_currentmailKeyReleased

    private void new_pass_confirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_pass_confirmFocusGained
        if (new_pass_confirm.getText().equals(" Retype the password")) {
            new_pass_confirm.setText("");
        }

    }//GEN-LAST:event_new_pass_confirmFocusGained

    private void new_pass_confirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_new_pass_confirmFocusLost
        // TODO add your handling code here:
        // TODO add your handling code here:
        kapa3.setIcon(null);
        if (new_pass_confirm.getText().equals("")) {
            new_pass_confirm.setText(" Retype the password");
        }
    }//GEN-LAST:event_new_pass_confirmFocusLost

    private void new_pass_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_pass_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_pass_confirmActionPerformed

    private void new_pass_confirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_pass_confirmKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_pass_confirmKeyPressed

    private void new_pass_confirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_pass_confirmKeyReleased
        // TODO add your handling code here:
        ImageIcon b = new ImageIcon();
        if (!(passsss.equals(confirm))) {
            ///vamartid/test1/images/V.png
            b = new ImageIcon(getClass().getResource("/vamartid/test1/images/X.png"));
            kapa3.setIcon(b);
        } else {
            b = new ImageIcon(getClass().getResource("/vamartid/test1/images/V.png"));
            kapa3.setIcon(b);
        }
    }//GEN-LAST:event_new_pass_confirmKeyReleased

    private void new_pass_confirmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_pass_confirmKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == ':') {
            evt.consume();  // ignore event
        } else if (evt.getKeyChar() == VK_BACK_SPACE) {
            String abc = new_pass_confirm.getText();
            if (!(abc.length() == 0)) {
                new_pass_confirm.setText(abc.substring(0, abc.length() - 1));
                String stringValueOf = String.valueOf(c);
                confirm = confirm + stringValueOf;
                evt.consume();
                new_pass_confirm.setText(new_pass_confirm.getText() + "*");
                //System.out.println(confirm);
            } else {
                new_pass_confirm.setText("");
                confirm = "";
            }
        } else {

            String stringValueOf = String.valueOf(c);
            confirm = confirm + stringValueOf;
            evt.consume();
            new_pass_confirm.setText(new_pass_confirm.getText() + "*");
            //System.out.println(confirm);
        }

    }//GEN-LAST:event_new_pass_confirmKeyTyped

    private void new_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_usernameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_new_usernameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Z_singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Z_singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Z_singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Z_singup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Z_singup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel backround;
    private javax.swing.JLabel close;
    private javax.swing.JButton create;
    private javax.swing.JLabel dragable;
    private javax.swing.JLabel kapa;
    private javax.swing.JLabel kapa2;
    private javax.swing.JLabel kapa3;
    private javax.swing.JLabel kapa4;
    private javax.swing.JLabel kapa5;
    private javax.swing.JButton min1;
    private javax.swing.JTextField new_birthday;
    private javax.swing.JTextField new_currentmail;
    private javax.swing.JTextField new_first;
    private javax.swing.JTextField new_last;
    private javax.swing.JTextField new_pass;
    private javax.swing.JTextField new_pass_confirm;
    private javax.swing.JTextField new_username;
    // End of variables declaration//GEN-END:variables
}
