/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vamartid.test1._email;

import java.awt.Frame;
import javax.swing.JFrame;
import java.awt.event.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author basilism
 */
public class Z_server extends javax.swing.JFrame {

    int xmouse;
    int ymouse;

    /**
     * Creates new form EmailMainGUI
     */
    public Z_server() {
        initComponents();
    }
    
    public Z_server(int port) throws Exception {
        new Thread() {
                public void run() {
                    try {
                        createServer(port);
                    } catch (Exception ex) {
                        Logger.getLogger(Z_server.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }.start();
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        min1 = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        load = new javax.swing.JLabel();
        dragable = new javax.swing.JLabel();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(302, 342));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min1.setToolTipText("Σμίκρυνση παραθύρου");
        min1.setBorder(null);
        min1.setBorderPainted(false);
        min1.setContentAreaFilled(false);
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.setFocusPainted(false);
        min1.setPreferredSize(new java.awt.Dimension(32, 9));
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                min1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                min1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                min1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                min1MouseReleased(evt);
            }
        });
        min1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min1ActionPerformed(evt);
            }
        });
        getContentPane().add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 0, 47, 32));

        close.setToolTipText("Κλείσιμο παραθύρου");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 0, 47, 32));

        load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vamartid/test1/images/loading.gif"))); // NOI18N
        getContentPane().add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 190, 100, 34));

        dragable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragableMouseDragged(evt);
            }
        });
        dragable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragableMousePressed(evt);
            }
        });
        getContentPane().add(dragable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 32));

        backround.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vamartid/test1/images/server.png"))); // NOI18N
        backround.setRequestFocusEnabled(false);
        getContentPane().add(backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 302, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void min1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min1ActionPerformed
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_min1ActionPerformed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        // TODO add your handling code here:
        close.setIcon(null);
        //System.out.println("Stopping Server");
        //server.stop();
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/xB.png"));
        close.setIcon(II);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        close.setIcon(null);

    }//GEN-LAST:event_closeMouseExited

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/xA.png"));
        close.setIcon(II);
    }//GEN-LAST:event_closeMousePressed

    private void min1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/B.png"));
        min1.setIcon(II);
    }//GEN-LAST:event_min1MouseEntered

    private void min1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseExited
        // TODO add your handling code here:
        min1.setIcon(null);

    }//GEN-LAST:event_min1MouseExited

    private void min1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseReleased
        // TODO add your handling code here:
        min1.setIcon(null);

    }//GEN-LAST:event_min1MouseReleased

    private void min1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/vamartid/test1/buttons/C.png"));
        min1.setIcon(II);
    }//GEN-LAST:event_min1MousePressed

    private void dragableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragableMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();

        ymouse = evt.getY();
    }//GEN-LAST:event_dragableMousePressed

    private void dragableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragableMouseDragged
        // TODO add your handling code here:

        int x = evt.getXOnScreen();

        int y = evt.getYOnScreen();

//System.out.println(x+" "+y);
        this.setLocation(x - xmouse, y - ymouse);

    }//GEN-LAST:event_dragableMouseDragged

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) throws IOException, Exception {
//       /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Z_server().setVisible(true);
//            }
//        });
//        MY_socket_SERVER.main();
//        
//        //System.out.println("Stopping Server");
//        //server.stop();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backround;
    private javax.swing.JLabel close;
    private javax.swing.JLabel dragable;
    private javax.swing.JLabel load;
    private javax.swing.JButton min1;
    // End of variables declaration//GEN-END:variables

    private void createServer(int port) throws Exception {
        //System.out.println("createServer "+port);
        MY_socket_SERVER.main(port);
    }
}
